### ISSUE TITLE
Add command line options & colors

### ISSUE THREAD

**Issue by jspizziri** [winton/gulp-docker#5]
It would be nice if the command line prompts showed the options, e.g.:

```
Push to docker registry? [Yn]
```

Also, color is always a nice touch 😄

**Comment by strawhatboy** [comment]
it would be nicer to avoid asking these questions (which image to build & push to docker registry) with configurations in gulpfile.js... (why need I still input something after running gulp ??? not nice for the CI :|

**Comment by wcalebgray** [comment]
+1 on what @strawhatboy said. It would be nice if you could specify in the options what image to build and if you should push or not so you don't need user input. This would be particularly helpful in a CI environment (as stated).

**Comment by wcalebgray** [comment]
@strawhatboy , I went digging and found that if you set some environment variables, you can avoid the prompts. Set IMAGE to the name of the image and PUSH to 1 to avoid the prompts. I created a PR to add this to the README: https://github.com/winton/gulp-docker/pull/9

**Comment by strawhatboy** [comment]
@wcalebgray , thx, glad to hear that! :)
